package render

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/khimananda/docker-nutrition-facts/internal/facts"
)

// Marker lets the GitHub Action find and update its own comment.
const Marker = "<!-- docker-nutrition-facts -->"

// Markdown renders a table suitable for a pull request comment.
func Markdown(r facts.Report) string {
	var b strings.Builder
	b.WriteString(Marker + "\n")
	fmt.Fprintf(&b, "### Nutrition Facts: `%s` (%s)\n\n", ShortName(r.Ref), r.Platform)
	b.WriteString("| Amount per serving | | % Daily Value |\n|---|--:|--:|\n")
	for _, row := range Rows(r) {
		if row.Kind != Fact {
			continue
		}
		label := mdEscape(row.Label)
		if row.Indent {
			label = "&nbsp;&nbsp;" + label
		} else if row.Bold {
			label = "**" + label + "**"
		}
		amt := mdEscape(row.Amount)
		if row.Bad {
			amt = "**" + amt + "** ⚠️"
		}
		fmt.Fprintf(&b, "| %s | %s | %s |\n", label, amt, row.DV)
	}
	contains := "no known allergens"
	if len(r.Allergens) > 0 {
		contains = "`" + strings.Join(r.Allergens, "`, `") + "`"
	}
	fmt.Fprintf(&b, "\n**Contains:** %s  \n**Grade: %s** (%d/100)\n", contains, r.Grade, r.Score)
	if len(r.Deductions) > 0 {
		b.WriteString("\n<details><summary>Why this grade</summary>\n\n")
		for _, d := range r.Deductions {
			fmt.Fprintf(&b, "- %s\n", d)
		}
		b.WriteString("\n</details>\n")
	}
	fmt.Fprintf(&b, "\n<sub>Daily values based on a 100 MB diet. %s Generated by <a href=\"https://github.com/khimananda/docker-nutrition-facts\">docker-nutrition-facts</a>.</sub>\n", r.Footnote)
	return b.String()
}

func mdEscape(s string) string { return strings.ReplaceAll(s, "|", `\|`) }

// JSON renders the report as indented JSON.
func JSON(r facts.Report) (string, error) {
	b, err := json.MarshalIndent(r, "", "  ")
	return string(b) + "\n", err
}
